"""
init_research.py — Scaffold a new autoresearch-skill project directory.

Usage:
    python init_research.py --goal "..." --metric "..." --direction {maximize|minimize} \
        [--target "..."] [--max-iterations 10] [--output ./my-research/]
"""

import argparse
import textwrap
from datetime import datetime
from pathlib import Path

RESEARCH_TEMPLATE = """\
# Research: {title}

## Goal
{goal}

## Success Metric
- **Metric:** {metric}
- **Target:** {target}
- **Direction:** {direction}

## Constraints
- **Max iterations:** {max_iterations}
- **Time budget per experiment:** 5 minutes
- **Pause for review every:** never
- **Evaluator:** {evaluator}
- **Keep policy:** {keep_policy}

## Current Approach
_Describe your current baseline here._

## Search Space
- **Allowed changes:** _Define what the agent can modify._
- **Forbidden changes:** _Define what must NOT change._

## Context & References
_Add relevant papers, docs, or URLs here._

---

## History
| # | Change | Metric | Result | Timestamp |
|---|--------|--------|--------|-----------|
| 0 | Baseline | TBD | -- | {date} |
"""

LOG_TEMPLATE = """\
# Research Log

> Auto-generated by init_research.py on {date}
> Goal: {goal}

---

"""

TSV_HEADER = "iteration\tmetric_value\tdelta\tdelta_pct\tstatus\tdescription\ttimestamp\n"
TSV_BASELINE = "0\tTBD\t-\t-\tbaseline\tInitial state\t{date}\n"


def goal_to_title(goal: str) -> str:
    """Convert a goal string to a short title (first 8 words, title-cased)."""
    words = goal.split()
    short = " ".join(words[:8])
    if len(words) > 8:
        short += "..."
    return short.title()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Scaffold a new autoresearch-skill project.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""\
            Example:
              python init_research.py \\
                --goal "Optimize sorting algorithm performance" \\
                --metric "execution_time_seconds" \\
                --direction minimize \\
                --target "< 0.5" \\
                --max-iterations 20 \\
                --output ./sort-research/
        """),
    )
    parser.add_argument("--goal", required=True, help="Research goal description.")
    parser.add_argument("--metric", required=True, help="Metric name to track (e.g. accuracy, execution_time_seconds).")
    parser.add_argument(
        "--direction",
        required=True,
        choices=["maximize", "minimize"],
        help="Whether to maximize or minimize the metric.",
    )
    parser.add_argument("--target", default="TBD", help="Target value or expression (e.g. '> 0.9', '< 0.5'). Default: TBD")
    parser.add_argument("--max-iterations", type=int, default=20, metavar="N", help="Maximum number of iterations. Default: 20")
    parser.add_argument("--output", default="./research/", metavar="PATH", help="Output directory. Default: ./research/")
    parser.add_argument("--evaluator", default=None, metavar="CMD",
        help="Evaluator command (e.g. 'python evaluate.py'). Must output JSON {pass:bool, score?:number}.")
    parser.add_argument("--keep-policy", default="score_improvement",
        choices=["score_improvement", "pass_only"],
        help="Keep policy: score_improvement (default) or pass_only.")
    return parser.parse_args()


def scaffold(goal: str, metric: str, direction: str, target: str, max_iterations: int, output: Path,
             evaluator: str | None = None, keep_policy: str = "score_improvement") -> None:
    date = datetime.now().strftime("%Y-%m-%d")
    title = goal_to_title(goal)
    evaluator_str = f"`{evaluator}`" if evaluator else "_(none — agent judges manually)_"

    # Create output directory (fail-safe: exist_ok=True)
    output.mkdir(parents=True, exist_ok=True)

    # Create workspace subdirectory
    workspace = output / "workspace"
    workspace.mkdir(exist_ok=True)

    # Write research.md
    research_md = output / "research.md"
    research_md.write_text(
        RESEARCH_TEMPLATE.format(
            title=title,
            goal=goal,
            metric=metric,
            target=target,
            direction=direction,
            max_iterations=max_iterations,
            evaluator=evaluator_str,
            keep_policy=keep_policy,
            date=date,
        )
    )

    # Write research_log.md
    log_md = output / "research_log.md"
    log_md.write_text(LOG_TEMPLATE.format(date=date, goal=goal))

    # Write autoresearch-results.tsv
    tsv_file = output / "autoresearch-results.tsv"
    tsv_file.write_text(TSV_HEADER + TSV_BASELINE.format(date=date))

    # Print success message
    print(f"\nResearch project scaffolded at: {output.resolve()}")
    print(f"\nFiles created:")
    print(f"  {research_md.resolve()}")
    print(f"  {log_md.resolve()}")
    print(f"  {tsv_file.resolve()}")
    print(f"  {workspace.resolve()}/")
    print(f"\nNext steps:")
    print(f"  1. Open research.md and fill in 'Current Approach' and 'Search Space'.")
    print(f"  2. Add context (papers, docs, code) under 'Context & References'.")
    print(f"  3. Run your baseline experiment and record it in the History table.")
    print(f"  4. Start iterating: modify → measure → log → repeat.")


def main() -> None:
    args = parse_args()
    output = Path(args.output)

    if output.exists() and any(output.iterdir()):
        print(f"Warning: output directory '{output}' already exists and is not empty.")
        answer = input("Continue and add files? [y/N] ").strip().lower()
        if answer != "y":
            print("Aborted.")
            return

    scaffold(
        goal=args.goal,
        metric=args.metric,
        direction=args.direction,
        target=args.target,
        max_iterations=args.max_iterations,
        output=output,
        evaluator=args.evaluator,
        keep_policy=args.keep_policy,
    )


if __name__ == "__main__":
    main()
